# Site
name: "Álvaro Durán"
title: "Álvaro Durán"
description: "Essays, Book Notes, Data Science!"
logo: 'assets/images/log.png'
tinylogo: 'assets/images/tinylog.png'
favicon: 'assets/images/logo.png'
baseurl:
google_analytics: 'UA-131540516-1'
disqus:
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
collections_dir: _collections

# Authors
authors:
  alvaro:
    name: Alvaro
    display_name: Álvaro
    gravatar:
    email: alvaro.duranb+blog@gmail.com
    web:
    twitter: https://twitter.com/oh_duran
    description:

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

collections:
  annual_letters:
    output: true
  articles:
    output: true
  books:
    output: true
  journal:
    output: true

videoSection: false
dailyCartoonSection: false
photoBoothSection: false
magazineSection: false
fromThisWeekSection: false
ourColumnistsSection: false
podcastsSection: false
previousCoverageSection: false
